import { Router, type IRouter } from "express";
import healthRouter from "./health";
import authRouter from "./auth";
import leadsRouter from "./leads";
import customersRouter from "./customers";
import estimatesRouter from "./estimates";
import jobsRouter from "./jobs";
import followUpsRouter from "./followUps";
import projectTasksRouter from "./projectTasks";
import marketPricesRouter from "./marketPrices";
import conversationsRouter from "./conversations";
import aiNotesRouter from "./aiNotes";
import uploadedPhotosRouter from "./uploadedPhotos";
import virtualAgentsRouter from "./virtualAgents";
import usersRouter from "./users";
import userPreferencesRouter from "./userPreferences";
import siteConfigRouter from "./siteConfig";
import aiRouter from "./ai";
import aiPhotoEstimateRouter from "./aiPhotoEstimate";
import googleReviewsRouter from "./googleReviews";
import googleBusinessRouter from "./googleBusiness";
import appointmentsRouter from "./appointments";
import designStudioRouter from "./designStudio";

const router: IRouter = Router();

router.use(healthRouter);
router.use(authRouter);
router.use(leadsRouter);
router.use(customersRouter);
router.use(estimatesRouter);
router.use(jobsRouter);
router.use(followUpsRouter);
router.use(projectTasksRouter);
router.use(marketPricesRouter);
router.use(conversationsRouter);
router.use(aiNotesRouter);
router.use(uploadedPhotosRouter);
router.use(virtualAgentsRouter);
router.use(usersRouter);
router.use(userPreferencesRouter);
router.use(siteConfigRouter);
router.use(aiRouter);
router.use(aiPhotoEstimateRouter);
router.use(googleReviewsRouter);
router.use(googleBusinessRouter);
router.use(appointmentsRouter);
router.use(designStudioRouter);

export default router;
